site_name: StreamController
nav:
  - Home: 
    - Home: index.md
    - Installation: installation.md
  - Plugin Development:
    - Introduction: plugin_dev/intro.md
    - Create Your Own:
      - Getting Started: plugin_dev/getting_started.md
      - 1. The Idea: plugin_dev/idea.md
      - 2. Setting Up Your Environment: plugin_dev/setup.md
      - 3. Introduction To Bases:
        - ActionBase.py: plugin_dev/bases/ActionBase_py.md
        - BackendBase.py: plugin_dev/bases/BackendBase_py.md
        - PluginBase.py: plugin_dev/bases/PluginBase_py.md
      - 4. The Plugin Template:
        - Overview: plugin_dev/plugin_template/overview.md
        - main.py: plugin_dev/plugin_template/main_py.md
        - SimpleAction.py: plugin_dev/plugin_template/SimpleAction_py.md
        # - BackendAction.py: plugin_dev/plugin_template/BackendAction_py.md
        # - backend.py: plugin_dev/plugin_template/backend_py.md
        # - __install__.py: plugin_dev/plugin_template/__install___py.md
        # - requirements.txt: plugin_dev/plugin_template/requirements_txt.md
        - manifest.json: plugin_dev/plugin_template/manifest_json.md
        - attribution.json: plugin_dev/plugin_template/attribution_json.md
      - 5. Modify The Template:
        - Overview:  plugin_dev/modify_template/overview.md
        - Add A Counter Action: plugin_dev/modify_template/AddCounter.md
        - Add Requirements: plugin_dev/modify_template/add_requirements.md
        - Add A Backend Action: plugin_dev/modify_template/add_a_backend_action.md
        - Add A Plugin Backend: plugin_dev/modify_template/add_a_plugin_backend.md
        - Add Config Options:
          - Intro To Gtk: plugin_dev/modify_template/config/gtk_intro.md
          - Stubs: plugin_dev/modify_template/config/stubs.md
          - Add Config Rows: plugin_dev/modify_template/config/add_config_rows.md
        # - Add A Backend To The Plugin: plugin_dev/modify_template/add_backend_to_plugin.md
        - Localization: plugin_dev/modify_template/localization.md
      - 6. Submitting: plugin_dev/submit.md
    - Advanced Concepts:
        - DeckController: plugin_dev/advanced_concepts/DeckController.md
        - Page Caching: plugin_dev/advanced_concepts/PageCaching.md
        - Signals: plugin_dev/advanced_concepts/Signals.md
  - Blog:
    - blog/index.md
  - Privacy:
    - privacy/index.md
  
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo_small.png
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  icon:
    repo: fontawesome/brands/github-alt
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: deep purple
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/weather-night
      name: Switch to light mode
    
repo_url: https://github.com/Core447/StreamController-docs
repo_name: Core447/StreamController-docs
edit_uri: edit/main/docs
    

extra:
  version:
    provider: mike
  social: 
    - icon: fontawesome/brands/github
      name: Core447
      link: https://github.com/Core447

copyright: Copyright &copy; 2024 Core447



# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - snippet:
      base_path: docs
  - blog
  - glightbox